Docs rules
coscene-io/docs pull request #10
Opened 2023-08-30 09:08 UTC by xiranyu01

2023-09-06 08:09 UTC, geoffliu requested changes
https://coscene0.feishu.cn/docx/R1bMdQOD8oNf8uxe2OicVITXnwc

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/1-intro.md
> +- **触发后的操作**：上传数据、创建一刻、创建&指派任务等
bags, too

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/2-configuration-rules.md
> +在项目中，进入「管理项目-数采与诊断规则」页面，点击【添加规则组】。
Link to rule doc

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/3-rule-format.md
> +其中，支持的时间戳格式如下（[参考文档](https://www.w3schools.com/python/python_datetime.asp)）：
Default, then config

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/3-rule-format.md
> +  - 定义日志中的关键事件，例如日志中包含某个字段
when 中任何一个规则触发以下所有 action

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/3-rule-format.md
> +  - 定义是否触发上传数据、创建一刻、创建&指派任务等操作
以上任何条件会触发 **所有** actions

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/3-rule-format.md
> +  - 规则组版本随刻行发布而更新
目前必须是 v1

2023-09-06 08:09 UTC, geoffliu commented on docs/4-receipts/data-diagnosis/3-rule-format.md
> +## 规则的标准格式
new page

2023-09-12 02:07 UTC, yujingz commented
@geoffliu im gonna do a merge first for better presentations on the site. if there are more things needs to be tweaked we can do another PR.

2023-09-12 02:07 UTC, yujingz approved these changes

2023-09-12 02:46 UTC, merged